/** 账单类型与方向选项：账单页表单与 AI 快记分流共用，不含服务端依赖 */
/** 类型对齐支付宝账单分类（截图参照），另保留学费/餐费/校车费三个学校专属类；排除纯支付机制类（信用借还/亲友代付/账户存取/退款） */
export const BILL_TYPES = [
  // 教育相关（本应用核心场景）
  "学费",
  "餐费",
  "校车费",
  "教育培训",
  "母婴亲子",
  // 保障与健康
  "保险",
  "医疗健康",
  // 日常生活
  "餐饮美食",
  "交通出行",
  "日用百货",
  "服饰装扮",
  "数码电器",
  "家居家装",
  "住房物业",
  "充值缴费",
  "生活费",
  "生活服务",
  "爱车养车",
  "运动户外",
  "美容美发",
  "宠物",
  "酒店旅游",
  "文化休闲",
  // 服务与其他
  "公共服务",
  "商业服务",
  "公益捐赠",
  "互助保障",
  "投资理财",
  "转账红包",
  "收入",
  "其他",
];

export const BILL_DIRECTIONS = ["支出", "收入"];

export const BILL_STATUSES = ["已缴", "未缴"];

export const BILL_TYPE_COLOR: Record<string, string> = {
  学费: "app-blue",
  餐费: "app-orange",
  校车费: "purple",
  教育培训: "warm-peach-pink",
  母婴亲子: "app-pink",
  保险: "app-teal",
  医疗健康: "app-green",
  餐饮美食: "app-orange",
  交通出行: "app-teal",
  日用百货: "app-yellow",
  服饰装扮: "app-pink",
  数码电器: "app-blue",
  家居家装: "brown",
  住房物业: "brown",
  充值缴费: "app-blue",
  生活费: "app-orange",
  生活服务: "lime-green",
  爱车养车: "purple",
  运动户外: "yellow-green",
  美容美发: "warm-peach-pink",
  宠物: "yellow-green",
  酒店旅游: "app-teal",
  文化休闲: "purple",
  公共服务: "app-blue",
  商业服务: "brown",
  公益捐赠: "app-red",
  互助保障: "app-green",
  投资理财: "app-yellow",
  转账红包: "app-red",
  收入: "app-green",
  其他: "default",
};

/** 饼图切片配色：与 BILL_TYPE_COLOR 同族，同 token 类型用深浅变体区分（支出/收入分开渲染，收入与支出类不会同图碰撞） */
export const BILL_TYPE_HEX: Record<string, string> = {
  学费: "#889df0",
  餐费: "#e59266",
  校车费: "#b77dee",
  教育培训: "#e18c6f",
  母婴亲子: "#f8a6b2",
  保险: "#82d5bb",
  医疗健康: "#8ac68a",
  餐饮美食: "#f2c29b",
  交通出行: "#58c2a2",
  日用百货: "#f7cd67",
  服饰装扮: "#f27d92",
  数码电器: "#5068d8",
  家居家装: "#9a835a",
  住房物业: "#bfa678",
  充值缴费: "#b3c2f7",
  生活费: "#d97a4a",
  生活服务: "#d1da49",
  爱车养车: "#9d55ea",
  运动户外: "#ecdf52",
  美容美发: "#cf6f52",
  宠物: "#cfc22f",
  酒店旅游: "#a8e2cf",
  文化休闲: "#d6b8f7",
  公共服务: "#6f86e8",
  商业服务: "#7d6a45",
  公益捐赠: "#fc736d",
  互助保障: "#66b368",
  投资理财: "#eab940",
  转账红包: "#e85c55",
  收入: "#8ac68a",
  其他: "#c4b89e",
};

/** 自定义类型（不在上表）时按序轮换取色 */
export const BILL_TYPE_HEX_FALLBACK = ["#f8a6b2", "#9a835a", "#d1da49", "#ecdf52", "#fc736d"];
